---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: CDC
  homepage: http://CDC.tencent.com
  email: isux@qq.com
  twitter: http://t.qq.com/tencent_cdc
  github: https://github.com/qianduan/qq-hd.font
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: qq-hd

  fullname: qq-hd
  familyname: qq-hd

  copyright: Copyright (C) 2013 by tencent cdc

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs:

  -
    css: qzone2
    code: 0xf802
    uid: e8a8af4d484f8a13f1b2a2e25177f099     
    search: [logo, qzone, isux]
  -
    css: qzone3
    code: 0xf803
    uid: 79f3f2a63fa7faa3499ab7d27be874de     
    search: [logo, qzone, isux]
  -
    css: qzone-lock
    code: 0xf804
    uid: 1953ac5f1f884e8b56b349222bca95d9     
    search: [logo, qzone, isux]
  -
    css: qzone-disabled
    code: 0xf805
    uid: f7ea69a750daee6748ca84f653a399f4     
    search: [logo, qzone, isux]
  -
    css: weibo2
    code: 0xf808
    uid: 9c963aeab2cd4a7435b5639833f652fa     
    search: [weibo,tencent]
  -
    css: at
    code: 0xf809
    uid: ed5644aab0bff71e6db74ac15f39f245     
    search: [at,tencent]
  -
    css: add
    code: 0xf80a
    uid: 3e58ddc8998807b91c809cc75626a01b     
    search: [add,tencent]
  -
    css: search
    code: 0xf80b
    uid: a8223e1b949d855c4ffe3eae7c346d4d     
    search: [search,tencent]
  -
    css: setting
    code: 0xf80c
    uid: 0abb66778c6bc4ecf94fdc2802e6ab7a     
    search: [setting,tencent]
  -
    css: clothes
    code: 0xf80d
    uid: 7bcbdd9b47d7bb15cdad8900601f0c0f     
    search: [clothes,tencent]
  -
    css: close
    code: 0xf80e
    uid: 45bbde8e88e618419a3611d01a8475fb
    search: [close,tencent]
  -
    css: delete
    code: 0xf80f
    uid: a99a22a32034bab4c50c8500c7cce31f     
    search: [delete,tencent]
  -
    css: person
    code: 0xf810
    uid: 69b994c5d51aaa6cad8a57604f8141c5 
    search: [person,tencent]
  -
    css: persons
    code: 0xf811
    uid: 91e3a9228759d2aaa2dd70d9f66e38e1 
    search: [person,tencent]
  -
    css: persons-disabled
    code: 0xf812
    uid: f0a193e2a64594d486130687056b7a38 
    search: [person,disabled,tencent]
  -
    css: male
    code: 0xf813
    uid: 3470b9bc220a42cb475ef076e6b551ab 
    search: [male,tencent]
  -
    css: female
    code: 0xf814
    uid: 69806d41b9907f8312ec4036d50e4273 
    search: [female,tencent]
  -
    css: write
    code: 0xf815
    uid: 084d8b3657f7fd6c0da3c91d0448e9d5 
    search: [write,tencent]
  -
    css: write2
    code: 0xf816
    uid: 29d26f42c39da97999ef84ddd0adf03c 
    search: [write,tencent]
  -
    css: reply
    code: 0xf817
    uid: cc12abec2b2044f9f64ef2402527d3b5 
    search: [reply,tencent]
  -
    css: reply2
    code: 0xf818
    uid: 372061bff5efc663a28f91b872240fbc 
    search: [reply,tencent]
  -
    css: comment
    code: 0xf819
    uid: 34d508cfc9cc2b7b79731d63dd0e1c70 
    search: [comment,tencent]
  -
    css: chat
    code: 0xf81a
    uid: a540be86a59b6edecef62752ad24d1f0 
    search: [chat,tencent]
  -
    css: retweet
    code: 0xf81b
    uid: 2257d21f245a5f423e1de0aefb5ffd84 
    search: [retweet,tencent]
  -
    css: microphone
    code: 0xf81c
    uid: da88c36949fef4035e74bae90fc153e0 
    search: [microphone,tencent]
  -
    css: microphone-disabled
    code: 0xf81d
    uid: 71f7fcda08a6ccdd21fa50a06a347cf4 
    search: [microphone,tencent]
  -
    css: sound
    code: 0xf826
    uid: edf3f468b175ab3b4dd31cd4d0a5865c 
    search: [sound,tencent]
  -
    css: camera
    code: 0xf81e
    uid: c9e7ad2c8e3dc3b67b5a4793ebbe3de1 
    search: [camera,tencent]
  -
    css: camera2
    code: 0xf81f
    uid: f7e63094c046bfe85ba8ab5bdbf7096c 
    search: [camera,tencent]
  -
    css: camera3
    code: 0xf820
    uid: 63bea61945057894406e5dbb308d9e74 
    search: [camera,tencent]
  -
    css: camera-disabled
    code: 0xf821
    uid: 7d21144e6042be6f68c61ce3900d0c65 
    search: [camera,disabled,tencent]
  -
    css: emotion
    code: 0xf822
    uid: c41b6732303cf6097b72764baff76286 
    search: [emotion,tencent]
  -
    css: emotion-add
    code: 0xf823
    uid: 0a21fcb6ecaf4956fbcc238ef592d65a 
    search: [emotion,add,tencent]
  -
    css: emotion-favorate
    code: 0xf824
    uid: e862f50ca71b0389f7ed7bc769eac8c4 
    search: [emotion,favorate,tencent]
  -
    css: heart
    code: 0xf825
    uid: 79d55f7d824c86104a4b093caba4a8e2 
    search: [heart,tencent]
  -
    css: share
    code: 0xf827
    uid: 081537f722bbdbc1b096415591b930f6 
    search: [share,tencent]
  -
    css: save
    code: 0xf828
    uid: aebce74b01075155f662a1b1c4542062 
    search: [save,tencent]
  -
    css: home
    code: 0xf829
    uid: 8a44b2e52359b510be2381f03ca679cb 
    search: [home,tencent]
  -
    css: profile
    code: 0xf82a
    uid: c083e154053d0c8ac16a2f213609d51d 
    search: [profile,tencent]
  -
    css: timing
    code: 0xf82b
    uid: bd5246fa15a7a0aa667ade9118e6eb4f 
    search: [timing,tencent]
  -
    css: time
    code: 0xf82c
    uid: baae97ed811994e116538a08a1a0c733 
    search: [time,tencent]
  -
    css: time2
    code: 0xf82d
    uid: a5ec1ebfa484a3f67f3beaf4ddd4ef71 
    search: [time,tencent]
  -
    css: countdown
    code: 0xf82e
    uid: 712860b4b37497154009f19f6e1c6c8a 
    search: [countdown,tencent]
  -
    css: plane
    code: 0xf82f
    uid: a5bb0e37dd683b881f654e7c7994fc41 
    search: [plane,tencent]
  -
    css: fullscreen
    code: 0xf830
    uid: 34495588058b4ed8086867c8629cb0cc 
    search: [fullscreen,tencent]
  -
    css: restore
    code: 0xf831
    uid: c8394c9fdc0ac94db106c730af80d981 
    search: [restore,tencent]
  -
    css: image
    code: 0xf832
    uid: 7047d50c147900b0263229723cf8dcac 
    search: [image,tencent]
  -
    css: graffiti
    code: 0xf833
    uid: ad31e700044e7e6396569ada7f1c28ce 
    search: [graffiti,tencent]
  -
    css: geolocation
    code: 0xf834
    uid: 233ae9c54d7bb6ff4697f03346d5ebd0 
    search: [location,geolocation,tencent]
  -
    css: keyboard
    code: 0xf835
    uid: 3cfc211e200de7512516b6ff6c3fe91d 
    search: [keyboard,tencent]
  -
    css: open-folder
    code: 0xf836
    uid: 7a081631ff7de56c6ec1415ff46fe1d2 
    search: [open,folder,tencent]
